Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false
      WebsiteConfiguration: # Capitalized 'W' in 'WebsiteConfiguration'
        IndexDocument: index.html
        ErrorDocument: error.html

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MyS3Bucket
      PolicyDocument:
        Id: MyPolicy # Capitalized 'I' in 'Id'
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "arn:aws:s3:::${MyS3Bucket}/*"

Outputs:
  websiteURL:
    Value: !GetAtt MyS3Bucket.WebsiteURL
    Description: URL of the website hosted on S3 bucket

  S3BucketSecureURL: # Corrected the spelling of 'S3BuketSecureURL'
    Value: !GetAtt MyS3Bucket.DomainName
    Description: S3 bucket secure URL
