AWSTemplateFormatVersion: '2010-09-09'
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      publicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: true
        RestrictPublicBuckets: false
      websiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

      deletionPolicy: Retain

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal: '*'
            Action:
              - s3:GetObject
            Resource: !Sub arn:aws:s3:::${S3Bucket}/*

  Output:
   websiteURL:
     Value: !GetAtt S3Bucket.WebsiteURL
     Description: URL of the S3 bucket

   S3BucketSeureURL:
     Value: !GetAtt S3Bucket.DomainName
     Description: S3 bucket secure URL

  